BEGIN;


DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS foods CASCADE;

CREATE TABLE  users(
    id SERIAL PRIMARY KEY, 
    username VARCHAR(70) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE foods (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  image_url TEXT,
  calories INT,
  created_at TIMESTAMP DEFAULT NOW(),
  user_id INT REFERENCES users(id) ON DELETE CASCADE
);

COMMIT;